In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import numpy as np
import gradio as gr

In [13]:
# Cell 1: Read and Prepare the Dataset 
df=pd.read_csv(r"C:\Users\Hassan\Desktop\Classification\Datasets\IRIS.csv")
print(df.columns)
print(df.shape)
print(df.head(150))


X = df[['sepal_length',  'sepal_width', 'petal_length','petal_width']]
y = df[ 'species']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
(150, 5)
     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-vir

In [14]:
#Cell 2 Task1 Support Vector Machine,Naïve Bayes,K-Nearest Neighbors Classifier

svm = SVC()
svm.fit(X_train, y_train)
svm_predictions = svm.predict(X_test)
svm_conf_matrix = confusion_matrix(y_test, svm_predictions)



nb = GaussianNB()
nb.fit(X_train, y_train)
nb_predictions = nb.predict(X_test)
nb_conf_matrix = confusion_matrix(y_test, nb_predictions)



knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_predictions = knn.predict(X_test)
knn_conf_matrix = confusion_matrix(y_test, knn_predictions)

# Display the confusion matrices of each
print("Confusion Matrix for SVM:")
print(svm_conf_matrix)

print("\nConfusion Matrix for Naïve Bayes:")
print(nb_conf_matrix)

print("\nConfusion Matrix for KNN:")
print(knn_conf_matrix)

Confusion Matrix for SVM:
[[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

Confusion Matrix for Naïve Bayes:
[[17  0  0]
 [ 0 17  2]
 [ 0  1 13]]

Confusion Matrix for KNN:
[[17  0  0]
 [ 0 19  0]
 [ 0  1 13]]


In [15]:
np.random.seed(2)

# Generate random indices for NaN values in 'sepal_length' column
sepal_length_nan_indices = np.random.choice(df.index, size=15, replace=False)
df.loc[sepal_length_nan_indices, 'sepal_length'] = np.nan
# Generate random indices for NaN values in 'petal_width' column
petal_width_nan_indices = np.random.choice(df.index, size=15, replace=False)
df.loc[petal_width_nan_indices, 'petal_width'] = np.nan

# Check for NaN values in each column
nan_counts = df.isnull().sum()
print(nan_counts)
print(df)


sepal_length    15
sepal_width      0
petal_length     0
petal_width     15
species          0
dtype: int64
     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             NaN          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[15

In [16]:
# Cell 4 task 3 Replace the NaN values with the mean 
Mean_df = df.assign(sepal_length=df['sepal_length'].fillna(df['sepal_length'].mean()), 
                   petal_width=df['petal_width'].fillna(df['petal_width'].mean()))
Mean_df



sepal_length  sepal_width  petal_length  petal_width         species
0        5.100000          3.5           1.4          0.2     Iris-setosa
1        4.900000          3.0           1.4          0.2     Iris-setosa
2        4.700000          3.2           1.3          0.2     Iris-setosa
3        5.894815          3.1           1.5          0.2     Iris-setosa
4        5.000000          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145      6.700000          3.0           5.2          2.3  Iris-virginica
146      6.300000          2.5           5.0          1.9  Iris-virginica
147      6.500000          3.0           5.2          2.0  Iris-virginica
148      6.200000          3.4           5.4          2.3  Iris-virginica
149      5.900000          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [17]:
# Cell 6 Task 4 - same as cell 2 but with the mean data set.

# Assuming features 1, 2, 3 as the input features and 'target' as the target variable for classification
X_mean = Mean_df[['sepal_length',  'sepal_width', 'petal_length','petal_width']]
y_mean = Mean_df['species']

# Split the filled data into training and testing sets
X_train_Mean, X_test_Mean, y_train_Mean, y_test_Mean = train_test_split(X_mean, y_mean, test_size=0.33, random_state=3)

# SVM Classifier on filled dataset
svm_classifier_filled = SVC()
svm_classifier_filled.fit(X_train_Mean, y_train_Mean)
svm_predictions_filled = svm_classifier_filled.predict(X_test_Mean)
svm_conf_matrix_filled = confusion_matrix(y_test_Mean, svm_predictions_filled)

# Naïve Bayes Classifier on filled dataset
nb_classifier_filled = GaussianNB()
nb_classifier_filled.fit(X_train_Mean, y_train_Mean)
nb_predictions_filled = nb_classifier_filled.predict(X_test_Mean)
nb_conf_matrix_filled = confusion_matrix(y_test_Mean, nb_predictions_filled)

# KNN Classifier on filled dataset
knn_classifier_filled = KNeighborsClassifier()
knn_classifier_filled.fit(X_train_Mean, y_train_Mean)
knn_predictions_filled = knn_classifier_filled.predict(X_test_Mean)
knn_conf_matrix_filled = confusion_matrix(y_test_Mean, knn_predictions_filled)

# Display confusion matrices on the filled dataset
print("Confusion Matrix for SVM on filled dataset:")
print(svm_conf_matrix_filled)

print("\nConfusion Matrix for Naïve Bayes on filled dataset:")
print(nb_conf_matrix_filled)

print("\nConfusion Matrix for KNN on filled dataset:")
print(knn_conf_matrix_filled)

Confusion Matrix for SVM on filled dataset:
[[18  0  0]
 [ 0 15  2]
 [ 0  0 15]]

Confusion Matrix for Naïve Bayes on filled dataset:
[[18  0  0]
 [ 0 15  2]
 [ 0  0 15]]

Confusion Matrix for KNN on filled dataset:
[[18  0  0]
 [ 0 14  3]
 [ 0  0 15]]


In [19]:
# Define the prediction function
def predict(sepal_length, sepal_width, petal_length, petal_width, classifier):
    input_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    
    if classifier == 'SVM':
        prediction = svm_classifier_filled.predict(input_data)
    elif classifier == 'Naive Bayes':
        prediction = nb_classifier_filled.predict(input_data)
    elif classifier == 'KNN':
        prediction = knn_classifier_filled.predict(input_data)
    
    return prediction[0]

In [21]:
interface = gr.Interface(
    fn=predict,
    inputs=[
        gr.Number(label="Sepal Length"),
        gr.Number(label="Sepal Width"),
        gr.Number(label="Petal Length"),
        gr.Number(label="Petal Width"),
        gr.Radio(choices=["SVM", "Naive Bayes", "KNN"], label="Classifier")
    ],
    outputs=gr.Textbox(label="Predicted Iris Species")
)

# Launch the interface
interface.launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


C:\Users\Hassan\Desktop\Classification\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
